name: CDK Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the CubeCobra application to deploy (v.*)
        required: true
        type: string
      environment:
        description: The deployment environment
        required: true
        default: development
        type: choice
        options:
          - development
          - production

jobs:
  plan:
    if: github.repository == 'dekkerglen/CubeCobraCDK'
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GITHUB_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: npm ci

      - run: npm test

      - run: npx cdk diff

  deploy:
    needs: plan
    runs-on: ubuntu-latest
    environment: production
    if: github.repository == 'dekkerglen/CubeCobraCDK'
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GITHUB_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CDK Deploy
        run: |
          npx cdk deploy --all --require-approval never \
            --context environment=${{ inputs.environment }} \
            --context version=${{ inputs.version }}